#!/bin/bash
# Usage:
#	cmd <#servers> <#start>
#
if [ $# -eq 0 ] || [ $# -eq 1 ]
then
echo "$0 : You must supply number of servers and start index"
exit 1
fi
NSERVERS=$1
j=$2
for ((  i = 1 ;  i <= $NSERVERS;  i++  ))
do
	echo ./scripts/run$j
	./scripts/run$j
	let j++
done
