#
# Aerospike Client Dockerfile
#
#

FROM debian:11

RUN apt update
RUN apt -y install software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt -y install build-essential
RUN apt -y install libssl-dev
RUN apt -y install libarchive-dev cmake rsync curl libcurl4-openssl-dev zip
RUN apt -y install python3 python3-dev python3-pip
RUN curl https://bootstrap.pypa.io/get-pip.py
# RUN apt -y install initscripts net-tools psmisc passwd
# RUN apt -y install wget openldap-devel
# RUN apt -y --enablerepo=powertools install lua-devel
# RUN apt -y install tcl tk tcl-devel tk-devel
# RUN apt -y install libffi libffi-devel gdbm-devel tk-devel
# RUN apt -y install xz-devel sqlite-devel readline-devel bzip2-devel ncurses-devel zlib-devel
# RUN apt -y install gcc-toolset-9-binutils
# RUN apt -y install libuv-devel
 
#  RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
#  RUN source ~/.bashrc
#  RUN nvm install 14.18.1 && nvm use 14.18.1
#  RUN npm install -g node-gyp
# cd ../../nodejs-expressions/
# DOWNLOAD=1 npm install
# node ~/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild

# for gdb build/install 
# ../configure --prefix=/usr --with-system-readline --with-python=/usr/bin/python3 && 
# make -j12 && make -C gdb/doc doxy && make -C gdb install
# install -d /usr/share/doc/gdb-10.2 && rm -rf gdb/doc/doxy/xml && cp -Rv gdb/doc/doxy /usr/share/doc/gdb-10.2
# RUN \
#  apt config-manager --set-enabled powertools \
#  && apt -y install texi2html texinfo doxygen
# install the built debugger

# VOLUME [/Users/ramarajpandian/code/src/:/code/src]
# RUN \
# cd /code/src/cpython-39/build
# ./configure  --with-valgrind
# make install
# cd ../../gdb-10.2/build/
# make -C gdb install
# install -d /usr/share/doc/gdb-10.2
# rm -rf gdb/doc/doxy/xml
# cp -Rv gdb/doc/doxy /usr/share/doc/gdb-10.2

RUN apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev \
    libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev -y
RUN apt -y install net-tools openssh-server wget libtool m4 automake

COPY ./requirements.txt /requirements.txt
RUN cd / && \
    wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tar.xz && \
    tar -xf Python-3.8.12.tar.xz && \
    mv ./Python-3.8.12 /opt/Python-3.8.12 && \
    cd /opt/Python-3.8.12/ && \
    ./configure --enable-optimizations --enable-shared && \
    make -j 8 && \
    make altinstall && \
    ldconfig /opt/Python-3.8.12 && \
    python3 -m pip install -r /requirements.txt

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
    . ~/.bashrc && \
    nvm install 16.14.0 && \
    nvm install 14.19.0 && \
    nvm install 12.22.10 && \
    nvm install 10.20.0 && \
    nvm use 16.14.0 && \
    npm install -g node-gyp && \
    npm install -g --force nodemon

RUN mkdir -p /var/run/sshd && \
    echo "mkdir -p /var/run/sshd" >> /etc/rc.local
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PermitEmptyPasswords yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    ssh-keygen -A

#RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64
#RUN chmod +x /usr/local/bin/dumb-init

EXPOSE 23 
# run the below command in container and connect to it using vscode
# python3 -m debugpy --listen 0.0.0.0:4001 --wait-for-client ./examples/client/get_async.py
EXPOSE 4002
EXPOSE 9230
COPY ./asadm-setup /asadmn-setup
COPY ./as-client_entrypoint.sh /as-client_entrypoint.sh
RUN ["chmod", "+x", "/as-client_entrypoint.sh"]

# VOLUME [/Users/ramarajpandian/code/src/:/code/src]

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc /tini.asc
# RUN gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 \
#  && gpg --batch --verify /tini.asc /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--", "/as-client_entrypoint.sh"]
CMD [""]

#How to
#docker container rm as-client1
#docker run -it --network=as-bridge -v /Users/ramarajpandian/code/src:/code/src as-client-debian11-dev:v1 /bin/bash
#docker image build -f Dockerfile-client-debian11.yml -t as-client-debian11-dev:v1 .