#
# Aerospike Client Dockerfile
#
#

FROM centos:8

RUN \
  dnf -y group install "Development Tools" \
  && dnf -y install openssl openssh-server openssl-devel \
  && dnf -y install libarchive cmake rsync libcurl-devel zip \
  && dnf -y install python38 python38-devel \
  && dnf -y install initscripts net-tools psmisc passwd \
  && dnf -y install wget openldap-devel \
  && dnf -y --enablerepo=powertools install lua-devel \
  && dnf -y install tcl tk tcl-devel tk-devel \
  && dnf -y install libffi libffi-devel gdbm-devel tk-devel \
  && dnf -y install xz-devel sqlite-devel readline-devel bzip2-devel ncurses-devel zlib-devel
  
COPY ./requirements.txt /requirements.txt
RUN python3.8 -m pip install -r /requirements.txt

#RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64
#RUN chmod +x /usr/local/bin/dumb-init

RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PermitEmptyPasswords yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    ssh-keygen -A

EXPOSE 22 
#expose debygpy port, refer entrypoint.sh
EXPOSE 4001

# VOLUME [/Users/ramarajpandian/code/src/:/code/src]

COPY ./asadm-setup /asadmn-setup
COPY ./as-client_entrypoint.sh /as-client_entrypoint.sh
RUN ["chmod", "+x", "/as-client_entrypoint.sh"]

# VOLUME [/Users/ramarajpandian/code/src/:/code/src]

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc /tini.asc
RUN gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 \
 && gpg --batch --verify /tini.asc /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--", "/as-client_entrypoint.sh"]
CMD [""]

#How to
#docker container rm as-client1
#docker build . -t as-client-centos8-dev:v1
#docker run -it --network=as-bridge -v /Users/ramarajpandian/code/src:/code/src as-client-centos8-dev:v1 /bin/bash