version: "3"
services:
    bob-cluster-a:
        image: as-server-centos8-dev:v1
        build: .
        volumes:
            - /Users/ramarajpandian/code/:/code/
        environment:
            - SERVICE_PORT=3000
            - TLS_SERVICE_PORT=4333
            - HB_PORT=9920
            - FABRIC_PORT=3002
            - INFO_PORT=3003
            - EEREPO=/code/src/aerospike/enterprise/aerospike-server-enterprise/
            - USE_EE=1
            - AS_CLUSTER_NAME=bob-cluster-a
            - TLS_CLUSTER_NAME=bob-cluster-a
            - NAMESPACE=test
        ports:
            - "2222:22"
        #     - "3000:3000"
        #     - "3002:3002"
        #     - "3003:3003"
        # network_mode: host
        cap_add: 
            - SYS_PTRACE
        networks:
            as-network:
                aliases:
                    - as-s1.as-network.com
    # bob-cluster-b:
    #     image: as-server-centos8-dev:v1
    #     build: .
    #     volumes:
    #         - /Users/ramarajpandian/code/:/code/
    #     environment:
    #         - SERVICE_PORT=3010
    #         - TLS_SERVICE_PORT=4343
    #         - HB_PORT=9920
    #         - FABRIC_PORT=3012
    #         - INFO_PORT=3013
    #         - EEREPO=/code/src/aerospike/enterprise/aerospike-server-enterprise/
    #         - USE_EE=1
    #         - AS_CLUSTER_NAME=bob-cluster-a
    #         - TLS_CLUSTER_NAME=bob-cluster-a
    #         - NAMESPACE=test
    #     ports:
    #         - "2223:22"
    #     #     - "3010:3010"
    #     #     - "3012:3012"
    #     #     - "3013:3013"
    #     #network_mode: host
    #     cap_add: 
    #         - SYS_PTRACE
    #     networks:
    #         as-network:
    #             aliases:
    #                 - as-s2.as-network.com
    # bob-cluster-c:
    #     image: as-server-centos8-dev:v1
    #     build: .
    #     volumes:
    #         - /Users/ramarajpandian/code/:/code/
    #     environment:
    #         - SERVICE_PORT=3020
    #         - TLS_SERVICE_PORT=4353
    #         - HB_PORT=9920
    #         - FABRIC_PORT=3022
    #         - INFO_PORT=3023
    #         - EEREPO=/code/src/aerospike/enterprise/aerospike-server-enterprise/
    #         - USE_EE=1
    #         - AS_CLUSTER_NAME=bob-cluster-a
    #         - TLS_CLUSTER_NAME=bob-cluster-a
    #         - NAMESPACE=test
    #     ports:
    #         - "2224:22"
    #     #     - "3020:3020"
    #     #     - "3022:3022"
    #     #     - "3023:3023"
    #     #network_mode: host
    #     cap_add: 
    #         - SYS_PTRACE
    #     networks:
    #         as-network:
    #             aliases:
    #                 - as-s3.as-network.com
    # importData:
    #     depends_on:
    #         - "bob-cluster-a"
    #         - "bob-cluster-b"
    #         - "bob-cluster-c"
    #     image: aerospike/aerospike-tools:latest
    #     container_name: tools
    #     volumes:
    #         - /Users/ramarajpandian/code/:/code/
    #     command: [ 'asrestore', '-h', 'bob-cluster-a', '-n', 'ssd-store', '-i', '/code/src/aerospike/enterprise/']
    #     cap_add: 
    #         - SYS_PTRACE
    #     security_opt:
    #         - seccomp:unconfined
    #     networks:
    #         as-network:
    #             aliases:
    #                 - as-c2.as-network.com
    as-client-node1:
        depends_on:
            - "bob-cluster-a"
            # - "bob-cluster-b"
            # - "bob-cluster-c"
        image: as-client-centos8-dev:v1
        # image: as-client-debian11-dev:v1
        build: .
        volumes:
            - /Users/ramarajpandian/code/:/code/
        environment:
            - DEBUGPY_PORT=4001
            - EEREPO=/code/src/aerospike/enterprise/aerospike-server-enterprise/
            - USE_EE=1
            - AS_INIT=1
            - ASD_HOST=bob-cluster-a
        ports:
            - "2225:22"
            - "4001:4001"
            - "9229:9229"
        #network_mode: host
        cap_add: 
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        networks:
            as-network:
                aliases:
                    - as-c1.as-network.com
    # as-client-node2:
    #     depends_on:
    #         - "bob-cluster-a"
    #         - "bob-cluster-b"
    #         - "bob-cluster-c"
    #         - "as-client-node1"
    #     image: as-client-alpine-dev:v1
    #     build: .
    #     volumes:
    #         - /Users/ramarajpandian/code/:/code/
    #     environment:
    #         - DEBUGPY_PORT=4001
    #         - EEREPO=/code/src/aerospike/enterprise/aerospike-server-enterprise/
    #         - USE_EE=1
    #         - AS_INIT=0
    #         - ASD_HOST=bob-cluster-a
    #     ports:
    #         - "2226:22"
    #         - "4002:4001"
    #         - "9230:9229"
    #     #network_mode: host
    #     cap_add: 
    #         - SYS_PTRACE
    #     security_opt:
    #         - seccomp:unconfined
    #     networks:
    #         as-network:
    #             aliases:
    #                 - as-c1.as-network.com
networks:
    as-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
                  ip_range: 172.28.0.0/24
                  gateway: 172.28.0.255
#How to
#docker image build -f ./Dockerfile-client.yml -t as-client-centos8-dev:v1 .
#docker image build -f ./Dockerfile-server.yml -t as-server-centos8-dev:v1 .

# docker-dev ramarajpandian$ docker network create \
# >   --driver=bridge \
# >   --subnet=172.28.0.0/16 \
# >   --ip-range=172.28.5.0/24 \
# >   --gateway=172.28.5.254 \
# >   as-bridge

# docker container stop docker-dev_as-server-node1_1
# docker container stop docker-dev_as-server-node2_1
# docker container stop docker-dev_as-server-node3_1
# docker container stop docker-dev_as-client-node1_1

# docker container rm docker-dev_as-server-node1_1
# docker container rm docker-dev_as-server-node2_1
# docker container rm docker-dev_as-server-node3_1
# docker container rm docker-dev_as-client-node1_1

#docker-compose up
#docker run -it --network=as-bridge -v /Users/ramarajpandian/code/src:/code/src as-client-centos8-dev:v1 /bin/bash
#docker exec -it docker-dev_as-server-node3_1 /usr/bin/bash

#docker run --rm -it --entrypoint bash -v /Users/ramarajpandian/code/src/:/code/src/ as-client-centos8-dev:v1

#docker-compose up --remove-orphans